### ISSUE TITLE
Custom Channel responding Forbidden on Ingoing messages

### ISSUE THREAD

**Issue by hilaldev** [respond-io/custom-channel-integration-example#1]
Hi,
I am using custom channel integration by following this link https://docs.respond.io/messaging-channels/custom-channel. I am using ingoing messages, so when we send request to ingoing channel it respond with Fobidden. I have tried from localhost and web host. 
Can you please assist with it?

**Comment by rbsherry** [comment]
Hi @hilaldev 
May I know if you are testing using curl code from the docs or using your own code implementation?
Can you share more details i.e. code snippet or may be curl code 

> Hi, I am using custom channel integration by following this link https://docs.respond.io/messaging-channels/custom-channel. I am using ingoing messages, so when we send request to ingoing channel it respond with Fobidden. I have tried from localhost and web host. Can you please assist with it?

**Comment by hilaldev** [comment]
Hi @rbsherry 
I have fixed the issue. It was caused by the contact number we were using to push the ingoing message.
Thank you for your response.
