### ISSUE TITLE
Custom Channel respond with "OK" but no file showing in Message

### ISSUE THREAD

**Issue by hilaldev** [respond-io/custom-channel-integration-example#2]
Hi, 
I have integrated the custom channel for incoming messages. The text messages are received with a channel response of "OK" and showing up in messages.
While I send media files to the channel as an incoming message, the channel responds with "OK" but the files are not showing in the messages. Attached is the example JSON I am sending to the custom channel

JSON
{"channelId":"MY CHANNEL ID","contactId":"+96566042327","events":[{"type":"attachment","mId":"621c8d79cf729","timestamp":1646038393850,"attachment":{"type":"image","url":"https:\/\/wordpress-737038-2469290.cloudwaysapps.com\/api\/downloads\/fssT6OlTBc.jpeg","mimeType":"image\/jpeg","description":null}}],"contact":{"phone":"+96566042327"}}

Response :
OK

Can you please assist with it?

Thank you

**Comment by KinzaRazzaq09** [comment]
> Hi, I have integrated the custom channel for incoming messages. The text messages are received with a channel response of "OK" and showing up in messages. While I send media files to the channel as an incoming message, the channel responds with "OK" but the files are not showing in the messages. Attached is the example JSON I am sending to the custom channel
> 
> JSON {"channelId":"MY CHANNEL ID","contactId":"+96566042327","events":[{"type":"attachment","mId":"621c8d79cf729","timestamp":1646038393850,"attachment":{"type":"image","url":"https://wordpress-737038-2469290.cloudwaysapps.com/api/downloads/fssT6OlTBc.jpeg","mimeType":"image/jpeg","description":null}}],"contact":{"phone":"+96566042327"}}
> 
> Response : OK
> 
> Can you please assist with it?
> 
> Thank you

Hi @hilaldev,
I have looked into the issue and it seems like the JSON payload that you are using is incomplete. (You might have copied from here: https://docs.respond.io/messaging-channels/custom-channel#sample-for-media-file )
But, for Incoming Media Messages to work, the above-mentioned JSON object should be wrapped inside the `message` object as defined in Step 2(Pass Messages to respond.io) here: https://docs.respond.io/messaging-channels/custom-channel

Do let me know if it works for you after following the correct format. Thanks

Attaching the screenshots for reference:
![image (36)](https://user-images.githubusercontent.com/100657020/156098723-e33160ac-7f1a-41e9-b02e-158d3a04a3d6.png)
![image (37)](https://user-images.githubusercontent.com/100657020/156098729-9ae98e58-fd67-4ffc-9e21-1bbcf9f54761.png)
![image](https://user-images.githubusercontent.com/100657020/156099343-d18d170c-8786-48ab-868a-99a873846f68.png)

**Comment by KinzaRazzaq09** [comment]
On another note, for `description` in attachment object, I noticed that you are sending as `null`. This should be empty string `""` if you do not want to send any description (should not send `null`).

**Comment by hilaldev** [comment]
Hi @KinzaRazzaq09,

You are correct. I changed the JSON payload and also changed the description from `null` to `''`. It worked and we are receiving media files.
Thank you

**Comment by KinzaRazzaq09** [comment]
Glad to know @hilaldev that it's working for you now.
Can close the issue now.

**Comment by zahassanyum** [comment]
Resolved
