### ISSUE TITLE
Custom channel webhook - returns 404 in body

### ISSUE THREAD

**Issue by pradeepmurugesan** [respond-io/custom-channel-integration-example#3]
Hello,
 
  I am trying to send a message to respond io's custom channel as mentioned in the [guide](https://docs.respond.io/messaging-channels/custom-channel)

Trying via postman gives me a 200 but the body has the following text
```
<h3 align="center">404 not Found!</h3>
```

I am not seeing the message in respond io. Can you kindly clarify what am I missing here. Attaching the screenshot of postman
![Screenshot 2022-03-23 at 08 05 26](https://user-images.githubusercontent.com/528317/159652275-18dc40e7-097a-4a8d-9773-84fff0f7b9c7.png)

**Comment by KinzaRazzaq09** [comment]
Hi @pradeepmurugesan 
I suspect the endpoint that you are trying to call is incomplete (i.e, `https://app.respond.io/custom/webhook/`). If you try to copy the endpoint from respond.io `Settings -> Channels` then you can find the correct endpoint (i.e, `https://app.respond.io/custom/channel/webhook/`)

**Comment by KinzaRazzaq09** [comment]
On a side note, our team will update the Guide as well.
Let me know if it fixes the problem for you.
Thanks

**Comment by pradeepmurugesan** [comment]
Hello @KinzaRazzaq09  thanks for taking a look.. Yes.. It works with the URL you provided..
