### ISSUE TITLE
Custom Channel respond with "OK" but no message received

### ISSUE THREAD

**Issue by civilcoder55** [respond-io/custom-channel-integration-example#4]
Hi,

Custom channel integration works fine, but when I try to send more than one message at the same time, I only receive the first message on the dashboard however, the response is 200 "OK".

Is there any rest time between requests?

**Comment by KinzaRazzaq09** [comment]
Hi @civilcoder55 
There is no rest time involved.
Can you share the screenshots of how have you set up the message request?

**Comment by civilcoder55** [comment]
![code](https://user-images.githubusercontent.com/58332033/164429817-825078b2-d525-435a-b7e8-5af0799bb801.png)

**Comment by KinzaRazzaq09** [comment]
@civilcoder55  This is the code snippet that you shared, can you share how does the final request look like after passing all the data?
Something similar to this
![image](https://user-images.githubusercontent.com/100657020/164617631-4d1806ec-0fc3-4589-860f-2ee5676e23f7.png)

**Comment by civilcoder55** [comment]
I always got "OK" but only the first message appears on the dashboard.
I must wait 30 seconds at least so that the next request is shown on the dashboard.

**Comment by KinzaRazzaq09** [comment]
Hi @civilcoder55 
Looks like you're not generating `mId` (message_id) in your request, a unique mId is required with each message to be sent to platform.
Let me know if it works for you.
Thanks.

**Comment by civilcoder55** [comment]
Hi @KinzaRazzaq09 
yes, now it's working fine. my bad I wasn't generating mid 
thank you for your help. 🙏
