### ISSUE TITLE
Custom Channel, Messages sent from another device (whatsapp)

### ISSUE THREAD

**Issue by justcami** [respond-io/custom-channel-integration-example#5]
Hi guys, Is there any way to enter outgoing messages from another device (main source as facebook business, whatsapp mobile) ? as it happens with chatapi - channel or messenger chanel.

**Comment by arvindrankalidas** [comment]
Hi @justcami , Would you be able to elaborate further? What is the use case you are trying to accomplish with Custom Channels?

Maybe a brief description of the user flow you are envisioning would be great as that would help contextualize the problem statement and we can assist from there on out accordingly.

**Comment by justcami** [comment]
Hi @arvindrankalidas, the idea is to connect an whatsapp ultramsg instance (Non official API) (https://docs.ultramsg.com/api/get/chats/messages). The respond.io final user normally (or sometimes) use the whatsapp from the mobile, so we need read and insert messages writting like that. Is that possible? I see this works in facebook messenger channels and chatapi.
![image](https://user-images.githubusercontent.com/33912789/173474020-c7659061-4f23-4ac3-887e-cbb43ab305a3.png)

Another question is How do I to insert an incomming reply message?

**Comment by KinzaRazzaq09** [comment]
Hi @justcami, do you mind sharing the request payload you are using to send echo messages?
Because the request payload should have `echo_message` value for `type` key in order for external messages to appear in respond.io platform.
![image](https://user-images.githubusercontent.com/100657020/173477500-afdf27e6-356f-4029-ae35-524e4787b802.png)

**Comment by justcami** [comment]
Excelent! going to try

**Comment by justcami** [comment]
Success!, do you know how to insert "reply to" inbound messages?

**Comment by KinzaRazzaq09** [comment]
Good to know the echo message issue got resolved for you. As for the "reply to", unfortunately, we do not support this at the moment for the custom channel but I can pass this request to the relevant team to create a **Feature Request** for you.

**Comment by KinzaRazzaq09** [comment]
Here is the link to the said feature request that you can track for its progress @justcami 
https://respond.canny.io/feature-request/p/custom-channel-support-incoming-reply-to-messages
