### ISSUE TITLE
Documentation for Message, Message Echo & Message Replies

### ISSUE THREAD

**Issue by vachan** [respond-io/custom-channel-integration-example#6]
In the [documentation section](https://docs.respond.io/messaging-channels/custom-channel#step-2-pass-messages-to-respond.io) it mentions about `Messages`, `Messaging Echoes` and `Messaging Receipts`. 

But the formatting or reference to `mId` is not mentioned.

---

Just wanted to understand how to use the `Messaging Echoes` and `Messaging Receipts` mediums to communicate back to Respond.io platform?

**Comment by KinzaRazzaq09** [comment]
Hi @vachan 
The documentation for Custom Channel has been updated already to cater to the information asked above and can be found in the following link.
https://docs.respond.io/messaging-channels/custom-channel#step-2-pass-messages-to-respond.io
