### ISSUE TITLE
Trailing `/message` issue with PHP

### ISSUE THREAD

**Issue by vachan** [respond-io/custom-channel-integration-example#7]
I am unable to rewrite the NGINX thus when working with PHP, I'm unable to strip off the `.php` suffix, leading to redirects and thus losing the ability to receive the payload.

Kindly let us know the reason and purpose for the trailing `/message` suffix?

**Comment by vachan** [comment]
Forgot to add the reference:
https://docs.respond.io/messaging-channels/custom-channel#step-3-handle-outgoing-messages-from-respond.io

When receiving message from Respond.io the suffix is being added `<API Base URL>/message`

**Comment by KinzaRazzaq09** [comment]
Hi @vachan 
Currently, we don't support custom endpoint paths. But the good news is we have created a Feature Request for this and you can upvote it to increase its priority and can track its progress from there.
https://respond.canny.io/feature-request/p/custom-channel-support-custom-endpoint-paths-for-outgoing-message-from-respondio
